version: '3'

services:
  # Configuration for Hub+Proxy
  jupyterhub:
    build: ./hub             # Build the container from the subfolder.
    container_name: jupyterhub_hub   # The service will use this container name.
    restart: unless-stopped
    volumes:                         # Give access to Docker socket.
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:                     # Env variables passed to the Hub process.
      - "DOCKER_JUPYTER_IMAGE=jupyter:wingstructure"
      - "DOCKER_NETWORK_NAME=web" 
      - "HUB_IP=jupyterhub_hub"
    labels:                          # Traefik configuration.
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:jupyter.akaflieg.tu-darmstadt.de"
    depends_on:
        - reverse-proxy

  # Configuration for reverse proxy
  reverse-proxy:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json

        #This can be uncommented to ensure image is ready on startup
  jupyterlab:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: jupyter:wingstructure
    command: echo
 
volumes:
  jupyterhub_data:

networks:
  default:
    external:
      name: web

