debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
	[entryPoints.http]
		address = ":80"
  		[entryPoints.http.redirect]
    			entryPoint = "https"
  	[entryPoints.https]
  		address = ":443"
	[entryPoints.https.tls]

[api]

[retry]

[file]
watch = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "hessen.akaflieg.tu-darmstadt.de"
watch = true
exposedByDefault = false
network = "web"

[acme]
email = "webmaster@akaflieg.tu-darmstadt.de"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[acme.httpChallenge]
entryPoint = "http"
